# Generated by Django 3.1.2 on 2022-12-20 16:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_assinatura_bairro_bandeira_cidade_consultor_estado_perfil_rede_sistemapdv_uso'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anydesk',
            field=models.TextField(blank=True, max_length=10, verbose_name='Acesso Anydesk'),
        ),
        migrations.AddField(
            model_name='post',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.bairro', verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='post',
            name='bandeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.bandeira', verbose_name='Bandeira do posto'),
        ),
        migrations.AddField(
            model_name='post',
            name='cep',
            field=models.CharField(default=1, max_length=8, verbose_name='CEP do endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.cidade', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='post',
            name='cnpj',
            field=models.CharField(default=1, max_length=15, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='complemento',
            field=models.CharField(default=1, max_length=100, verbose_name='Complemento endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='consultor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.consultor', verbose_name='Consultor ou revendedor'),
        ),
        migrations.AddField(
            model_name='post',
            name='contato_oficina',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='DDD + Telefone da oficina'),
        ),
        migrations.AddField(
            model_name='post',
            name='contato_pdv',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contato do sistema PDV'),
        ),
        migrations.AddField(
            model_name='post',
            name='data_fim',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de encerramento'),
        ),
        migrations.AddField(
            model_name='post',
            name='email_oficina',
            field=models.EmailField(max_length=50, null=True, verbose_name='Email da loja'),
        ),
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='post',
            name='inscricao_estadual',
            field=models.CharField(default=1, max_length=10, verbose_name='Inscricao estadual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='integrado',
            field=models.BooleanField(blank=True, default=True, verbose_name='Esta Integrado?'),
        ),
        migrations.AddField(
            model_name='post',
            name='numero_residencia',
            field=models.CharField(default=1, max_length=8, verbose_name='Numero da residência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='pagando',
            field=models.BooleanField(default=True, verbose_name='O cliente esta pagando?'),
        ),
        migrations.AddField(
            model_name='post',
            name='perfil_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.perfil', verbose_name='Perfil do cliente'),
        ),
        migrations.AddField(
            model_name='post',
            name='rede_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.rede', verbose_name='Rede ou grupo'),
        ),
        migrations.AddField(
            model_name='post',
            name='sistema_pdv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.sistemapdv', verbose_name='Sistema do PDV'),
        ),
        migrations.AddField(
            model_name='post',
            name='teamviewer',
            field=models.TextField(blank=True, max_length=10, verbose_name='Acesso TeamViewer'),
        ),
        migrations.AddField(
            model_name='post',
            name='tipo_assinatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.assinatura', verbose_name='Tipo de assinatura'),
        ),
        migrations.AddField(
            model_name='post',
            name='uso_momento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.uso', verbose_name='Modo de uso atual'),
        ),
        migrations.AddField(
            model_name='post',
            name='valor_mensalidade',
            field=models.CharField(default=11, max_length=10, verbose_name='Valor da mensalidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem_post',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Foto do posto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado_post',
            field=models.BooleanField(default=False, verbose_name='Publicar no site'),
        ),
    ]
