# Generated by Django 3.1.2 on 2022-08-13 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('telefone', models.TextField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('mensagem', models.TextField(max_length=250, verbose_name='Mensagem')),
                ('mostrar', models.BooleanField(default=True)),
                ('data_contato', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
