# Generated by Django 3.1.2 on 2022-08-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(max_length=100, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.TextField(blank=True, max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
