# Generated by Django 3.1.2 on 2022-12-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='post_comentario',
        ),
    ]
