# Generated by Django 3.1.2 on 2022-12-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_remove_comentario_post_comentario'),
        ('oficinas', '0002_auto_20221218_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='oficina_comentario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oficinas.oficina'),
            preserve_default=False,
        ),
    ]
