# Generated by Django 4.0.1 on 2022-01-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_produto_brotinho_produto_esfiha_produto_especial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vegana',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
