# Generated by Django 4.0.1 on 2022-01-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_produto_vegana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='brotinho',
            new_name='destilados',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='esfiha',
            new_name='esfihasdoce',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='especial',
            new_name='esfihastradicionais',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='pizza',
            new_name='pizzasdoces',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='tradicional',
            new_name='pizzasespeciais',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='vegana',
            new_name='pizzastradicionais',
        ),
        migrations.AddField(
            model_name='produto',
            name='pizzasveganas',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='refrigerantes',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='sobremesas',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='vinhos',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
