# Generated by Django 3.1.2 on 2022-07-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_rename_brotinho_produto_destilados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='acessorios',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cordas',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='instrumentos',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='kits',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='livros',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='makulele',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='passeiocoloridas',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='promocoes',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='uniformes',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='vestuarios',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('V', 'Variavel'), ('S', 'Simples'), ('M', 'Moleton'), ('C', 'Calcados'), ('I', 'Infantil'), ('A', 'Adulto'), ('B', 'Berimbau'), ('P', 'Pandeiro'), ('R', 'Recoreco'), ('L', 'Livro')], default='V', max_length=1),
        ),
    ]
