# Generated by Django 3.1.2 on 2022-07-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_auto_20220705_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='ingredientes',
            new_name='detalhes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='destilados',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='esfihasdoce',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='esfihastradicionais',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='pizzasdoces',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='pizzasespeciais',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='pizzastradicionais',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='pizzasveganas',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='refrigerantes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='sobremesas',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='vinhos',
        ),
    ]
