# Generated by Django 4.0.1 on 2022-08-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_auto_20220705_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='detalhes',
            new_name='ingredientes',
        ),
    ]
