# Generated by Django 3.1.2 on 2022-11-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_rename_detalhes_produto_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='acessorios',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cordas',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='instrumentos',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='kits',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='livros',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='makulele',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='passeiocoloridas',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='promocoes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='uniformes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='vestuarios',
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('C', 'Completo'), ('S', 'Simples')], default='V', max_length=1),
        ),
    ]
