# Generated by Django 3.1.2 on 2022-06-29 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20220628_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcontato',
            name='usuario_contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formcontato',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='formcontato',
            name='mensagem',
            field=models.TextField(max_length=250, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='formcontato',
            name='mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formcontato',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='formcontato',
            name='telefone',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Telefone'),
        ),
    ]
