# Generated by Django 4.0.1 on 2022-08-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220628_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='projeto_imagens/%Y/%m/')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('subtitulo', models.TextField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('descricaocurta', models.TextField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('descricaolonga', models.TextField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('mostrar', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='projeto_imagens/%Y/%m/')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('subtitulo', models.TextField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('descricaocurta', models.TextField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('descricaolonga', models.TextField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('mostrar', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
