# Generated by Django 4.0.1 on 2022-08-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_eventos_projetos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descricaocurta',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descricaolonga',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Descrição longa'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='subtitulo',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Sub titulo'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaocurta',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaolonga',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Descrição longa'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='subtitulo',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Sub titulo'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo'),
        ),
    ]
