# Generated by Django 4.0.1 on 2022-08-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_eventos_descricaocurta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descricaocurta',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descricaolonga',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Descrição longa'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaocurta',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaolonga',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Descrição longa'),
        ),
    ]
