# Generated by Django 4.0.1 on 2022-08-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_eventos_descricaocurta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
