# Generated by Django 4.0.1 on 2022-08-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_eventos_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='projeto_imagens/%Y/%m/')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo')),
                ('subtitulo', models.TextField(blank=True, max_length=50, null=True, verbose_name='Sub titulo')),
                ('descricaocurta', models.TextField(blank=True, max_length=150, null=True, verbose_name='Descrição curta')),
                ('descricaolonga', models.TextField(blank=True, max_length=800, null=True, verbose_name='Descrição longa')),
                ('mostrar', models.BooleanField(blank=True, default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('projetos_sociais', models.BooleanField(blank=True, default=True)),
                ('eventos', models.BooleanField(blank=True, default=True)),
                ('categoria', models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='home.categoria')),
            ],
        ),
    ]
