# Generated by Django 3.1.2 on 2022-08-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_projetos_slug_alter_eventos_foto_capa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.DeleteModel(
            name='Projetos',
        ),
    ]
