# Generated by Django 3.1.2 on 2022-12-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20221215_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='projetos_sociais',
            new_name='oficinas',
        ),
        migrations.AddField(
            model_name='post',
            name='foto_logo',
            field=models.ImageField(blank=True, null=True, upload_to='projeto_imagens/%Y/%m/'),
        ),
    ]
