# Generated by Django 3.1.2 on 2022-12-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_post_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mapa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
