# Generated by Django 3.1.2 on 2022-12-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20221217_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='oficinas',
        ),
    ]
