# Generated by Django 3.1.2 on 2023-01-05 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionalidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('exibir_funcionalidade', models.BooleanField(default=True, verbose_name='Exibir esta funcionalidade?')),
                ('funcionalidade_especialista', models.BooleanField(default=False, verbose_name='Funcionalidade de Especialista?')),
                ('funcionalidade_GerenteLoja', models.BooleanField(default=False, verbose_name='Funcionalidade de Gerente de Loja?')),
                ('funcionalidade_GerenteRede', models.BooleanField(default=False, verbose_name='funcionalidade de Gerente de rede?')),
                ('titulo_funcionalidade', models.CharField(max_length=255, verbose_name='Título')),
                ('conteudo_funcionalidade', models.TextField(verbose_name='Conteúdo')),
                ('icone_funcionalidade', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem do icone da funcionalidade')),
                ('subtitulo_funcionalidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
