# Generated by Django 3.1.2 on 2023-01-05 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionalidades',
            name='autor_publicacao',
            field=models.ForeignKey(default=6345, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user', verbose_name='Autor da publicação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionalidades',
            name='subtitulo_funcionalidade',
            field=models.CharField(max_length=255, verbose_name='Sub-título da funcionalidade'),
        ),
        migrations.AlterField(
            model_name='funcionalidades',
            name='titulo_funcionalidade',
            field=models.CharField(max_length=255, verbose_name='Título da funiocnalidade'),
        ),
    ]
