# Generated by Django 3.1.2 on 2023-01-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0002_auto_20230104_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionalidades',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug do final do link'),
        ),
    ]
