# Generated by Django 3.1.2 on 2023-01-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0003_funcionalidades_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionalidades',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug do final do link'),
        ),
    ]
