# Generated by Django 3.1.2 on 2022-09-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Academia')),
                ('mestre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mestre')),
                ('contraMestre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contra Mestre')),
                ('professor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Professor')),
                ('dias', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dias')),
                ('horario_de', models.CharField(blank=True, max_length=50, null=True, verbose_name='Horário de')),
                ('horario_ate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Horário ate')),
                ('endereco', models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço')),
                ('pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pagamento')),
                ('mostrar', models.BooleanField(default=True)),
            ],
        ),
    ]
