# Generated by Django 3.1.2 on 2022-09-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='modalidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modalidade'),
        ),
    ]
