# Generated by Django 3.1.2 on 2022-09-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_aulas_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='online',
            field=models.BooleanField(default=True, verbose_name='Aula online'),
        ),
        migrations.AddField(
            model_name='aulas',
            name='presencial',
            field=models.BooleanField(default=True, verbose_name='Aula presencial'),
        ),
        migrations.AlterField(
            model_name='aulas',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='Publicar'),
        ),
    ]
