# Generated by Django 3.1.2 on 2022-12-18 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0002_remove_comentario_post_comentario'),
        ('categorias', '0001_initial'),
        ('oficinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_oficina', models.CharField(max_length=255, verbose_name='Título')),
                ('data_publicacao_oficina', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('conteudo_oficina', models.TextField(verbose_name='Conteúdo')),
                ('excerto_oficina', models.TextField(verbose_name='Excerto')),
                ('imagem_oficina', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem')),
                ('publicado_oficina', models.BooleanField(default=False, verbose_name='Publicar oficina')),
                ('categoria_oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categoria', verbose_name='Categoria')),
                ('gestor_oficina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Gestor Oficina')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
